name: csi-unity
version: 2.2.0
appVersion: 2.2.0
kubeVersion: ">= 1.20 <= 1.23"
description: |
  Unity CSI (Container Storage Interface) driver Kubernetes
  integration. This chart includes everything required to provision via CSI as
  well as a Unity StorageClass.
keywords:
- csi
- storage
sources:
- https://github.com/dell/csi-unity
maintainers:
- name: DellEMC
