# Represents number of certificate secrets, which user is going to create for ssl authentication. (unity-cert-0..unity-cert-n)
# Minimum value should be 1
certSecretCount: 1

# "volumeNamePrefix" defines a string prepended to each volume created by the CSI driver.
volumeNamePrefix: csivol

# "snapNamePrefix" defines a string prepended to each snapshot registered by the CSI driver.
snapNamePrefix: csi-snap

# The default pull policy is IfNotPresent which causes the Kubelet to skip pulling an image
# if it already exists. If you would like to always force a pull, use "Always"
imagePullPolicy: IfNotPresent

# controllerCount is controller replication count to maintain high availability.
# controllerCount value should be >= 1
controllerCount: 2

#To set nodeSelectors and tolerations for controller.
controller:
  #You may define a nodeSelector if desired for the controllers.
  nodeSelector:
  #   node-role.kubernetes.io/master: ""

  #You may define tolerations if desired for the controllers.
  tolerations:
  # - key: "node-role.kubernetes.io/master"
  #   operator: "Exists"
  #   effect: "NoSchedule"

# "node" allows to configure node specific parameters
node:
  # Determines the DNS Policy of the Node service.
  # ClusterFirstWithHostNet is the recommended and default DNS policy for the driver.
  # Prior to v1.6 of the driver, the default DNS policy was ClusterFirst.
  # In certain scenarios, users might need to change the default dnsPolicy.
  dnsPolicy: "ClusterFirstWithHostNet"

# Podmon is an optional feature under development and tech preview.
# Enable this feature only after contact support for additional information
podmon:
  enabled: false
  image:
#  controller:
#    args:
#      - "-csisock=unix:/var/run/csi/csi.sock"
#      - "-labelvalue=csi-unity"
#      - "-driverPath=csi-unity.dellemc.com"
#      - "-mode=controller"
#  node:
#    args:
#      - "-csisock=unix:/var/lib/kubelet/plugins/unity.emc.dell.com/csi_sock"
#      - "-labelvalue=csi-unity"
#      - "-driverPath=csi-unity.dellemc.com"
#      - "-mode=node"
#      - "-leaderelection=false"

# Time interval to add node info to array. Default 15 minutes. Minimum value should be 1.
# If your specifies 0, then time is set to default value.
# syncNodeInfoInterval has been deprecated and will be removed from use in values.yaml in a future release.
# This can be now configured from secret.json/secret.yaml.
# The value from secret can be loaded dynamically by the driver without requiring a re-installation and has higher precedence.
syncNodeInfoInterval: 15

# Flag to enable sharing of volumes across multiple pods within the same node in RWO access mode.
# Setting allowRWOMultiPodAccess to "true" will allow multiple pods on the same node
# to access the same RWO volume. This behavior conflicts with the CSI specification version 1.3
# NodePublishVolume descrition that requires an error to be returned in this case.
# However some other CSI drivers support this behavior and some customers desire this behavior.
# Kubernetes could make a change at their discretion that would preclude our ability to support this option.
# Customers use this option at their own risk.

# allowRWOMultiPodAccess has been deprecated and will be removed from use in values.yaml in a future release.
# This can be now configured from secret.json/secret.yaml.
# The value from secret can be loaded dynamically by the driver without requiring a re-installation and has higher precedence.
allowRWOMultiPodAccess: "false"


