logLevel: "Info"                    # LogLevel is used to set the logging level of the driver. This can be Info/Debug/Warn/Error

syncNodeInfoInterval: 15            # Time interval to add node info to array. Default 15 minutes. Minimum value should be 1.
                                    # If this is specified as 0, then time is set to default value.
                                    
allowRWOMultiPodAccess: "false"     # Flag to enable sharing of volumes across multiple pods within the same node in RWO access mode.
                                    # Setting allowRWOMultiPodAccess to "true" will allow multiple pods on the same node
                                    # to access the same RWO volume. This behavior conflicts with the CSI specification version 1.3
                                    # NodePublishVolume descrition that requires an error to be returned in this case.
                                    # However some other CSI drivers support this behavior and some customers desire this behavior.
                                    # Kubernetes could make a change at their discretion that would preclude our ability to support this option.
                                    # Customers use this option at their own risk.                              
                                    
maxUnityVolumesPerNode: 0           # Maximum number of volumes that controller can publish to the node.
                                    # If value is zero CO SHALL decide how many volumes of this type can be published by the controller to the node.
                                    

storageArrayList:
 - arrayId: "ABC00000000001"        # Array ID of Unity
   username: "user"                 # username for connecting to Unity Unisphere REST API server
   password: "password"             # password for connecting to Unity Unisphere REST API server
   endpoint: "https://1.2.3.4/"     # HTTPS endpoint of the Unity Unisphere REST API server
   skipCertificateValidation: true  # indicates if client side validation of server's certificate can be skipped
   isDefault: true                  # default array (would be used by storage classes without arrayId parameter)
   
  - arrayId: "ABC00000000002"
    username: "user"
    password: "password"
    endpoint: "https://1.2.3.5/"
    skipCertificateValidation: true
   