# This is a sample manifest for utilizing the topology feature and mount options.
# PVCs created using this storage class will be scheduled 
# only on the nodes with FC connectivity to the array

# Change all instances of <ARRAY_ID> to the array serial ID of the unisphere instance used

# Provide mount options through "mountOptions" attribute 
# to create PVCs with mount options.

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: unity-<ARRAY_ID>-fc
provisioner: csi-unity.dellemc.com
reclaimPolicy: Delete
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
parameters:
  protocol: FC #Protocol that will be used for provisioning. FC denotes that the provisioning will be via Fibre Channel
  arrayId: <ARRAY_ID> #Serial Id of the array that will be used for provisioning. Example APM00000000000
  storagePool: <STORAGE_POOL> #Insert Storage pool CLI Id here. Example pool_0
  thinProvisioned: true #Boolean to choose value of thinProvisioned while creating a new volume
  isDataReductionEnabled: true #Boolean to choose value of isDataReductionEnabled while creating a new volume
  tieringPolicy: <TIERING_POLICY> #Insert Tiering policy that is to be used for provisioning here. Example 0
  hostIOLimitName: <HOST_IO_LIMIT_NAME> #Insert Host IO Limit Name that is to be used for provisioning here. 
allowedTopologies:
  - matchLabelExpressions:
      - key: csi-unity.dellemc.com/<array_id>-fc
        values:
          - "true"
          
mountOptions: ["<mountOption1>", "<mountOption2>", ..., "<mountOptionN>"]
